In [1]:
import os
import struct
import random
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [2]:
with open("data/training_set_labels", 'rb') as flbl:
    magic, num = struct.unpack(">II", flbl.read(8))
    lbl = np.fromfile(flbl, dtype=np.int8)

with open("data/training_set_images", 'rb') as fimg:
    magic, num, rows, cols = struct.unpack(">IIII", fimg.read(16))
    img_view = np.fromfile(fimg, dtype=np.uint8).reshape(len(lbl),rows,cols)
    
img = img_view.reshape(len(lbl),rows*cols)
idx = np.random.randint(60000, size=500)
img = img[idx,:]
lbl = lbl[idx]
img = img/255.0
NUM_OF_DATA = len(img)
img = np.concatenate((np.ones((1,NUM_OF_DATA)), img.T)).T


In [3]:
img = img[0:500]
NUM_OF_DATA = 500

In [20]:
img

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.]])

In [4]:
# idx = np.random.randint(60000, size=10)
# rand_arr = img_view[idx,:]
# for i in range(0,10):
#     plt.imshow(rand_arr[i], cmap='gray_r')
#     plt.show()

In [5]:
alpha = 0.8
max_it = 500
landa = 0.000001
theta_vals = []

In [6]:
def sigmoid(z):  
    return 1 / (1 + np.exp(-z))

In [7]:
def cost(theta, X, y):
    m = NUM_OF_DATA
    first = np.multiply(-y, np.log(sigmoid(np.dot(X , theta.T))))
    second = np.multiply((1 - y), np.log(1 - sigmoid(np.dot(X , theta.T))))
    reg = (landa / 2 * len(X)) * np.sum(np.power(theta, 2))
    return np.sum(first - second) / (len(X)) + reg

In [8]:
def gradient(theta, X, y):  
    parameters = len(X[0])
    grad = np.zeros(parameters)
    error = sigmoid(np.dot(X,theta.T)) - y
    m = NUM_OF_DATA
    for i in range(parameters):
        term = np.multiply(error, X[:,i])
        if (i == 0):
            grad[i] = np.sum(term) / m
        else:
            grad[i] = (np.sum(term) / m) + ((landa / m) * theta[i])
    return grad

In [9]:
def classification(x,y):
    m = len(x)
    n = len(x[0])
    theta = np.zeros(n)
    count_it = 0
    J = []
    while count_it < max_it :
        count_it += 1
        if count_it % 100 == 0:
            print count_it
        npd = np.dot(x , theta)
        npde = np.exp(-npd)
        h = 1./(1 + npde)
        j = cost(theta,x,y)
        g = gradient(theta,x,y)
        theta = theta - alpha * g
        J.append(j)
    return theta

In [10]:
def create_lable(lable_val , lables):
    return np.array([int (x==lable_val) for x in lables])

In [11]:
create_lable(2, lbl)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [22]:
lbl

array([6, 8, 7, 1, 1, 3, 0, 8, 6, 9, 3, 7, 4, 8, 1, 0, 2, 7, 4, 0, 4, 1, 8,
       1, 5, 7, 3, 4, 9, 9, 8, 3, 2, 9, 1, 4, 7, 2, 2, 7, 1, 7, 8, 2, 9, 6,
       7, 8, 1, 6, 7, 6, 3, 9, 6, 7, 1, 2, 9, 7, 1, 9, 3, 0, 6, 1, 3, 8, 8,
       7, 8, 8, 0, 4, 8, 8, 3, 6, 1, 7, 7, 6, 6, 7, 8, 6, 8, 5, 0, 2, 1, 1,
       4, 2, 4, 6, 4, 7, 3, 9, 4, 0, 7, 0, 5, 2, 8, 2, 8, 3, 4, 1, 3, 0, 5,
       3, 1, 9, 5, 6, 2, 6, 1, 4, 2, 8, 0, 5, 6, 3, 8, 9, 1, 8, 1, 6, 9, 8,
       9, 6, 8, 9, 3, 0, 3, 5, 1, 3, 9, 1, 1, 1, 4, 3, 7, 1, 0, 5, 9, 8, 2,
       2, 9, 1, 7, 0, 3, 2, 0, 7, 9, 1, 3, 0, 2, 2, 4, 0, 5, 4, 3, 8, 5, 0,
       2, 3, 8, 6, 7, 3, 1, 0, 5, 5, 1, 7, 8, 7, 5, 1, 9, 5, 5, 5, 6, 6, 4,
       1, 5, 9, 1, 8, 4, 1, 1, 9, 4, 1, 8, 6, 7, 7, 7, 3, 7, 7, 8, 4, 7, 9,
       3, 3, 4, 6, 1, 8, 6, 6, 1, 2, 1, 6, 8, 0, 6, 9, 8, 8, 0, 1, 1, 1, 2,
       8, 5, 5, 1, 2, 5, 5, 0, 2, 5, 2, 9, 0, 8, 1, 9, 0, 4, 4, 8, 3, 3, 4,
       2, 6, 6, 3, 0, 6, 4, 4, 4, 9, 9, 3, 2, 9, 0, 6, 3, 7, 3, 3, 3, 7, 7,
       3, 1,

In [12]:
def one_vs_all_classification(k):
    for i in range(0,k):
        print "------",i
        y = create_lable(i,lbl)
        theta = classification(img , y)
        theta_vals.append(theta)

In [17]:
one_vs_all_classification(10)
print theta_vals

------ 0
100
200
300
400
500
------ 1
100
200
300
400
500
------ 2
100
200
300
400
500
------ 3
100
200
300
400
500
------ 4
100
200
300
400
500
------ 5
100
200
300
400
500
------ 6
100
200
300
400
500
------ 7
100
200
300
400
500
------ 8
100
200
300
400
500
------ 9
100
200
300
400
500
[array([ -1.08136420e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e

In [14]:
theta = np.array(theta_vals)
print theta.shape

(10, 785)


In [15]:
with open("t10k-labels.idx1-ubyte", 'rb') as flbl:
    magic, num = struct.unpack(">II", flbl.read(8))
    lbl_test = np.fromfile(flbl, dtype=np.int8)

with open("t10k-images.idx3-ubyte", 'rb') as fimg:
    magic, num, rows, cols = struct.unpack(">IIII", fimg.read(16))
    img_test_view = np.fromfile(fimg, dtype=np.uint8).reshape(len(lbl_test),rows,cols)
    img_test = img_test_view.reshape(len(lbl_test),rows*cols)

img_test = img_test/255.
img_test = np.concatenate((np.ones((1,len(lbl_test))), img_test.T)).T

idx_test = random.randint(0,len(lbl_test))
plt.imshow(img_test_view[idx_test], cmap='gray_r')
plt.show()
          
ans = sigmoid(np.dot(theta,img_test[idx_test].T))
for i in range(0,10):
    print "predicted probability for value ",i," is: ",ans[i]
print "---"
print "predicted value is: " , ans.argmax()
print "real value is: ",lbl_test[idx_test]

IOError: [Errno 2] No such file or directory: 't10k-labels.idx1-ubyte'